version: "3.3"

services:
  app:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile_django
    ports:
      - "8000:8000"
    links:
      - db
    volumes:
      - ../app:/application/app
  db:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile_postgres
    ports:
      - "5432:5432"
